config/routes.rb
Rails.application.routes.draw do

  devise_scope :admin do
    get 'admins/editSupervisor/:id', to: 'admins/registrations#editSupervisor', as: 'editSupervisor'
  end

  devise_scope :admin do
    put 'admins/updateSupervisor/:id', to: 'admins/registrations#updateSupervisor', as: 'updateSupervisor'
  end

  devise_scope :admin do
    delete 'admins/deleteSupervisor/:id', to: 'admins/registrations#deleteSupervisor', as: 'deleteSupervisor'
  end

  devise_scope :user do
    put 'users/edit', to: 'users/registrations#updateUser', as: 'updateUser'
  end

  put "/autos/cambiarEstado/:auto_id", to: "autos#cambiarEstado", as: "cambiarEstado"


  resources :autos, only: [:new, :create, :edit, :update]
  resources :precios
  resources :reportes, only: [:show]
	resources :locations, only: :create
  # devise_for :supervisors, controllers: {
  #   sessions: 'supervisors/sessions'
  # }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:index]
  resources :admins, only: [:index]

  # as :admin do
  #   get '/admins', :to => 'admins#estadisticas', :as => :admins_root # Rails 3
  # end

  as :user do
    # generate route that recives the id of a auto
    get 'users', :to => 'users#index', :as => :users_root # Rails 3
  end

  # get "admins/edit/:id", to: "admins/registrations#edit"
  # put "admins/edit/:id", to: "admins/registrations#update"

  get '/users/vehiculo/:id', :to => 'users#vehiculo', :as => :vehiculo
  get '/admins/listar_usuarios', :to => 'admins#listar_usuarios'
  get '/admins/listar_no_validados', :to => 'admins#listar_no_validados'
  get '/admins/listar_supervisores', :to => 'admins#listar_supervisores'
  get '/autos', :to => 'autos#listadoDeAutos'

  get '/admins/showUser/:id', :to => 'admins#showUser', as: 'showUser'

  root "main#home"

  get '/wallets/:user_id', :to => 'wallets#mostrar_wallet'
  put '/wallets/cargar_saldo/:user_id', :to => 'wallets#cargar_saldo'

  get '/precios', :to => 'precios#index'
  post '/precios/editarPrecio', :to => 'precios#editarPrecio'

  put '/cards/create/', :to => 'cards#create'
  get '/users/vista_mapa', :to => 'users#vista_mapa'
  get '/cards/create', :to => 'cards#new', :as => 'new_card'

  put '/admins/updateUserStatus/:user_id', :to => 'admins#updateUserStatus'

  get '/users/vista_alquiler', :to => 'users#vista_alquiler'

  put '/users/finalizar_alquiler', :to => 'users#finalizar_alquiler'

  post '/users/alquilar/:auto_id', :to => 'users#alquilar'

  get '/users/certificado', :to => 'users#certificado'

  get '/abrir_cerrar/:id', :to => 'users#abrir_cerrar'

  get 'alquiler/resumen', :to => 'users#resumen', :as => 'resumen'

  get '/admins/listado_reportes/pendientes', :to => 'reportes#index_pendientes'

  get '/admins/listado_reportes/atendidos', :to => 'reportes#index_atendidos'

  get '/admins/listado_reportes/finalizados', :to => 'reportes#index_finalizados'

  get '/admins/estadisticas', :to => 'admins#estadisticas'

  get '/admins/estadisticas/alquileres', :to => 'admins#estadisticas_alquileres'

  get '/admins/estadisticas/ganancias', :to => 'admins#estadisticas_ganancias'

  get '/admins/estadisticas/reportes', :to => 'admins#estadisticas_reportes'

  get '/admins/estadisticas/en_curso', :to => 'admins#estadisticas_en_curso'

  get '/users/reportes/new', :to => 'reportes#new', :as => 'new_reporte'

  post '/users/reportes/create', :to => 'reportes#create', :as => 'create_reporte'

  put '/users/prolongar_alquiler', :to => 'users#prolongar_alquiler'

  put '/atender_reporte/:id', :to => 'reportes#atender_reporte'

  put '/finalizar_reporte/:id', :to => 'reportes#finalizar_reporte'

  get '/admins/historial_de_uso/:id', :to => 'admins#historial_de_uso'

  get '/alquiler/show/:id', :to => 'admins#show_alquiler'

  get '/', :to => 'main#home'

  #match "*path" => redirect("/"), via: [:get, :post]   #DEJAR SIEMPRE AL FINAL

end

app/views/admins/edit.html.erb
<h2>Edit <%= @admin.first_name%></h2>
edit path for admin

<%= resource %>


<%= form_for(@admin, urL: registration_path(@admin) , method: :put, html: {class: "form-group"}) do |f| %>
<%# <%= form_for(@admin, ) do |f| %> %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
<%#
  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <%# <div>Currently waiting confirmation for: <%= resource.unconfirmed_email </div> %>
  <%# <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <%# fields for first_name, last_name, phone, birth_date, is_admin %>
  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :Apellido %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :Teléfono %><br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :Fecha_de_nacimiento %><br />
    <%= f.date_field :birth_date %>
  </div>

  <div class="field mt-2 mb-2">
      <%= f.label "Es administrador", sytle:"margin-right:2px" %>
      <%= f.check_box :is_admin, style:"margin-top:2px" %>
    </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>





  <div class="actions ">
    <%= f.submit "Update", class:"btn btn-primary p-1 mt-2" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(@admin), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/admins/estadisticas.html.erb
<html>

<head>
    <script src="https://kit.fontawesome.com/38e5d75ed7.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Varela Round' rel='stylesheet'>
</head>

<h1 class="font bold pt-5 text-center"> Hola <%= @admin.first_name%>! Aquí hay un resumen del día de hoy </h1>

<div style="height: 80%; justify-content: center; align-items: center; display: flex; flex-direction: column;">

    <div class="container d-flex">
        <% if @admin.is_admin == false %>
        <span></span>
        <%else%>
        <div class="btn container d-flex align-items-stretch border shadow m-3" id="ganancias">
            <i class="align-self-center fa-solid fa-dollar-sign fa-5x m-3" style="color: #f59e3e"></i>
            <div class="align-self-center text-center m-auto">
                <h5 class="font"> Dinero recaudado hoy</h5>
                <h2 class="font bold" style="color: #f59e3e"> $ <%= @dinero_recaudado_hoy %> </h2>
            </div>
        </div>
        <%end%>

        <div class="btn container d-flex border shadow m-3" id="en-curso">
            <i class="fa-solid fa-car-side align-self-center fa-5x m-3" style="color: #f59e3e"></i>
            <div class="align-self-center text-center m-auto">
                <h5 class="font"> Alquileres en curso </h5>
                <% if @usuarios_alquilando.empty? %>
                    <h2 class="font bold" style="color: #f59e3e"> Ninguno </h2>
                <% else %>
                    <h2 class="font bold" style="color: #f59e3e"> <%= @usuarios_alquilando.size %> </h2>
                <% end %>
            </div>
        </div>

    </div>

    <div class="container d-flex">
        <div class="btn container d-flex border shadow m-3" id="alquileres">
            <i class="fa-solid fa-chart-pie align-self-center fa-5x m-3" style="color: #f59e3e"></i>
            <div class="align-self-center text-center m-auto">
                <h5 class="font"> Auto más pedido hoy </h5>
                <% if @mas_alquilado_hoy.nil? %>
                    <h2 class="font bold" style="color: #f59e3e"> Ninguno </h2>
                <% else %>
                    <h2 class="font bold" style="color: #f59e3e"> <%= @mas_alquilado_hoy.modelo %> </h2>
                <% end %>
            </div>
        </div>

        <div class="btn container d-flex border shadow m-3" id="reportes">
            <i class="align-self-center fa-solid fa-flag fa-5x m-3" style="color: #f59e3e"></i>
            <div class="align-self-center text-center m-auto">
                <h5 class="font"> Reportes hechos hoy </h5>
                <% if @reportes_hoy.nil? %>
                    <h2 class="font bold" style="color: #f59e3e"> Ninguno </h2>
                <% else %>
                    <h2 class="font bold" style="color: #f59e3e"> <%= @reportes_hoy  %> </h2>
                <% end %>
            </div>
        </div>
    </div>

</div>

<style>

    .font{
        font-family: 'Varela Round';
    }

    .border{
        background-color: #F5F5F5;
        border-color: #F5F5F5;
        border: 2px solid black;
        border-radius: 25px;
    }

</style>

<script>

    var alquileres = document.getElementById("alquileres");
    alquileres.addEventListener("click", function(){
        window.location.href = "/admins/estadisticas/alquileres";
    });

    var ganancias = document.getElementById("ganancias");
    if (ganancias != null){
            ganancias.addEventListener("click", function(){
            window.location.href = "/admins/estadisticas/ganancias";
        });
    }


    var enCurso = document.getElementById("en-curso");
    enCurso.addEventListener("click", function(){
        window.location.href = "/admins/estadisticas/en_curso";
    });

    var uso = document.getElementById("reportes");
    uso.addEventListener("click", function(){
        window.location.href = "/admins/estadisticas/reportes";
    });

</script>

</html>

app/views/admins/estadisticas_alquileres.html.erb
<head>
    <link href='https://fonts.googleapis.com/css?family=Varela Round' rel='stylesheet'>
    <script src="https://kit.fontawesome.com/38e5d75ed7.js" crossorigin="anonymous"></script>
</head>

<div class="text-center">

    <h1 class="mt-4 mb-5 font">Estadísticas sobre reservas</h1>

    <% if @alquileres.empty? %>
        <h3 class="font">No hay reservas registradas</h3>
    <% else %>

        <div class="container d-flex">

            <div class="container d-flex border shadow me-3">
                <!--<i class="align-self-center fa-solid fa-star fa-5x m-3" style="color: #46a85a"></i>-->
                <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="#46a85a" class="m-3 bi bi-triangle-fill align-self-center" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767L7.022 1.566z"/>
                </svg>
                <div class="align-self-center text-center m-auto">
                    <h5 class="font"> Auto más usado históricamente </h5>
                    <h2 class="font bold"> <%= @mas_alquilado.modelo %> </h2>
                </div>
            </div>

            <div class="container d-flex border shadow ms-3">
                <!--<i class="fa-solid fa-star align-self-center fa-5x m-3" style="color: #a84659"></i>-->
                <svg xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="#a84659" class="m-3 bi bi-triangle-fill align-self-center" viewBox="0 0 16 16" id="icon">
                    <path fill-rule="evenodd" d="M7.022 1.566a1.13 1.13 0 0 1 1.96 0l6.857 11.667c.457.778-.092 1.767-.98 1.767H1.144c-.889 0-1.437-.99-.98-1.767L7.022 1.566z"/>
                </svg>
                <div class="align-self-center text-center m-auto">
                    <h5 class="font"> Auto menos usado históricamente </h5>
                    <h2 class="font bold"> <%= @menos_alquilado.modelo %> </h2>
                </div>
            </div>
            
        </div>

        <br>

        <!-- GRAFICOS GENERALES -->
        <div class="container pt-4 border shadow">
            <h3 class="d-flex align-self-start font bold">Reservas en general</h3>
            <nav class="pt-3">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">

                    <button class="nav-link active" id="genn-week-tab" data-bs-toggle="tab"
                        data-bs-target="#genn-week" type="button" role="tab" aria-controls="genn-week" aria-selected="true">
                        Última semana
                    </button>

                    <button class="nav-link" id="genn-month-tab" data-bs-toggle="tab"
                        data-bs-target="#genn-month" type="button" role="tab" aria-controls="genn-month" aria-selected="false">
                        Último mes
                    </button>

                    <button class="nav-link" id="genn-year-tab" data-bs-toggle="tab"
                        data-bs-target="#genn-year" type="button" role="tab" aria-controls="genn-year" aria-selected="false">
                        Último año
                    </button>

                    <button class="nav-link" id="genn-hist-tab" data-bs-toggle="tab"
                        data-bs-target="#genn-hist" type="button" role="tab" aria-controls="genn-hist"
                        aria-selected="false">
                        Histórico
                    </button>

                </div>
            </nav>
            
            <div class="tab-content pt-3" id="nav-tabContent" style="background-color: white">

                <div class="tab-pane fade show active" id="genn-week" role="tabpanel" aria-labelledby="genn-week-tab">
                    <%= line_chart @alquileres.group_by_day(:fecha_alquiler, format: "%d/%m/%Y", last: 7).count %>
                </div>

                <div class="tab-pane fade" id="genn-month" role="tabpanel" aria-labelledby="genn-month-tab">
                    <%= line_chart @alquileres.group_by_day(:fecha_alquiler, format: "%d/%m/%Y", last: 30).count %>
                </div>

                <div class="tab-pane fade" id="genn-year" role="tabpanel" aria-labelledby="genn-year-tab">
                    <%= line_chart @alquileres.group_by_month(:fecha_alquiler, format: "%m/%Y").count %>
                </div>

                <div class="tab-pane fade" id="genn-hist" role="tabpanel" aria-labelledby="genn-hist-tab">
                    <%= line_chart @alquileres.group_by_day(:fecha_alquiler, format: "%d/%m/%Y").count %>
                </div>

            </div>

            <br>

        </div>

        <br>

        <div class="container pt-4 border shadow">
            <h3 class="d-flex align-self-start font bold">Reservas de los autos</h3>
            <nav class="pt-3">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">

                    <button class="nav-link active" id="gen-week-tab" data-bs-toggle="tab"
                        data-bs-target="#gen-week" type="button" role="tab" aria-controls="gen-week" aria-selected="true">
                        Última semana
                    </button>

                    <button class="nav-link" id="gen-month-tab" data-bs-toggle="tab"
                        data-bs-target="#gen-month" type="button" role="tab" aria-controls="gen-month" aria-selected="false">
                        Último mes
                    </button>

                    <button class="nav-link" id="gen-year-tab" data-bs-toggle="tab"
                        data-bs-target="#gen-year" type="button" role="tab" aria-controls="gen-year" aria-selected="false">
                        Último año
                    </button>

                    <button class="nav-link" id="gen-hist-tab" data-bs-toggle="tab"
                        data-bs-target="#gen-hist" type="button" role="tab" aria-controls="gen-hist"
                        aria-selected="false">
                        Histórico
                    </button>

                </div>
            </nav>
            
            <div class="tab-content pt-3" id="nav-tabContent" style="background-color: white">

                <div class="tab-pane fade show active" id="gen-week" role="tabpanel" aria-labelledby="gen-week-tab">
                    <%= line_chart @autos.map { |auto|
                        {name: auto.modelo, data: @alquileres.where(auto_id: auto.id).group_by_day(:fecha_alquiler, last: 7, format: "%d/%m/%Y").count}
                    } %>
                </div>

                <div class="tab-pane fade" id="gen-month" role="tabpanel" aria-labelledby="gen-month-tab">
                    <%= line_chart @autos.map { |auto|
                        {name: auto.modelo, data: @alquileres.where(auto_id: auto.id).group_by_day(:fecha_alquiler, last: 30, format: "%d/%m/%Y").count}
                    } %>
                </div>

                <div class="tab-pane fade" id="gen-year" role="tabpanel" aria-labelledby="gen-year-tab">
                    <%= line_chart @autos.map { |auto|
                        {name: auto.modelo, data: @alquileres.where(auto_id: auto.id).group_by_month(:fecha_alquiler, last: 12, format: "%m/%Y").count}
                    } %>
                </div>

                <div class="tab-pane fade" id="gen-hist" role="tabpanel" aria-labelledby="gen-hist-tab">
                    <%= line_chart @autos.map { |auto|
                        {name: auto.modelo, data: @alquileres.where(auto_id: auto.id).group_by_day(:fecha_alquiler, format: "%d/%m/%Y").count}
                    } %>
                </div>

            </div>

            <br>

        </div>

        <br>

        <!-- GRAFICOS POR AUTO -->
        <div class="contaner border shadow">

            <div class="d-flex">

                <h3 class=" p-3 align-self-center font bold">Reservas por auto</h3>

                <!-- Dropdown -->
                <div class="dropdown ms-auto p-3 align-self-center">
                    <button class="btn btn-lg btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdown-button">
                        <b><%=@autos.first.modelo%></b> - <%=@autos.first.patente%>
                    </button>
                    <ul class="dropdown-menu" id="eleccion-auto">
                        <%for @auto in @autos do %>
                            <% patente=@auto.patente %>
                            <li>
                                <a class="dropdown-item" id="<%=patente%>_time" type="button"><%=@auto.modelo%> - <%=@auto.patente%></a>
                            </li>
                        <% end %>
                    </ul>
                </div>

            </div>

            <!-- container por auto -->
            <div id="grafico-por-auto">

                <% i = 0%>

                <% for @auto in @autos do %>
                    <% i += 1 %>

                    <% patente = @auto.patente %>

                    <% if i == 1 %>

                        <div class="container" id="<%=patente%>-container">

                    <% else %>

                        <div class="container" id="<%=patente%>-container" hidden="true">

                    <% end %>
                            <nav class="pt-3">

                                <div class="nav nav-tabs" role="tablist">
                                
                                    <button class="nav-link active" id="<%=patente%>-week-tab" data-bs-toggle="tab" data-bs-target="#<%=patente%>-week" type="button" role="tab"
                                        aria-controls="<%=patente%>-week" aria-selected="true">
                                        Ultima semana
                                    </button>

                                    <button class="nav-link" id="<%=patente%>-month-tab" data-bs-toggle="tab" data-bs-target="#<%=patente%>-month" type="button" role="tab"
                                        aria-controls="<%=patente%>-month" aria-selected="false">
                                        Ultimo mes
                                    </button>

                                    <button class="nav-link" id="<%=patente%>-year-tab" data-bs-toggle="tab" data-bs-target="#<%=patente%>-year" type="button" role="tab"
                                        aria-controls="<%=patente%>-year" aria-selected="false">
                                        Ultimo año
                                    </button>

                                    <button class="nav-link" id="<%=patente%>-hist-tab" data-bs-toggle="tab" data-bs-target="#<%=patente%>-hist" type="button" role="tab"
                                        aria-controls="<%=patente%>-hist" aria-selected="false">
                                        Histórico
                                    </button>
                                
                                </div>

                            </nav>

                            <div class="tab-content pt-3" style="background-color: white">

                                <div class="tab-pane fade show active" id="<%=patente%>-week" role="tabpanel" aria-labelledby="<%patente%>-week-tab">
                                    <%= column_chart @alquileres.where(auto_id: @auto.id).group_by_day(:fecha_alquiler, last: 7, format: "%d/%m/%Y" ).count %>
                                </div>

                                <div class="tab-pane fade" id="<%=patente%>-month" role="tabpanel" aria-labelledby="<%patente%>-month-tab">
                                    <%= column_chart @alquileres.where(auto_id: @auto.id).group_by_day(:fecha_alquiler, last: 30, format: "%d/%m/%Y" ).count %>
                                </div>

                                <div class="tab-pane fade" id="<%=patente%>-year" role="tabpanel" aria-labelledby="<%patente%>-year-tab">
                                    <%= column_chart @alquileres.where(auto_id: @auto.id).group_by_month(:fecha_alquiler, last: 12, format: "%m/%Y" ).count %>
                                </div>

                                <div class="tab-pane fade" id="<%=patente%>-hist" role="tabpanel" aria-labelledby="<%patente%>-hist-tab">
                                    <%= column_chart @alquileres.where(auto_id: @auto.id).group_by_day(:fecha_alquiler, format: "%d/%m/%Y" ).count %>
                                </div>

                            </div>

                            <br>

                        </div>

                <% end %>

            </div>
        </div>

        <br>    
    
    <%end%>

</div>







<style>

    .border{
        background-color: #F5F5F5;
        border: 2px solid black;
        border-radius: 15px;
    }

    .font{
        font-family: 'Varela Round';
    }

</style>

<script>

    var eleccion = document.getElementById("eleccion-auto");

    eleccion.addEventListener("click", function(e){
        var seleccionado = e.target.innerHTML;
        var id = e.target.id;
        var patente = id.split("_")[0];
        console.log(patente);

        modelo = seleccionado.split("-")[0];
        boldModelo = "<b>" + modelo + "</b>";

        var dropdownButton = document.getElementById("dropdown-button");
        dropdownButton.innerHTML = boldModelo + " - " + patente;


        var graficoPorAuto = document.getElementById("grafico-por-auto");
        var graficoPorAutoChildren = graficoPorAuto.children;
        for (var i = 0; i < graficoPorAutoChildren.length; i++) {
            graficoPorAutoChildren[i].hidden = true;
        }

        var conteiner = document.getElementById(patente + "-container");
        conteiner.hidden = false;

    });

    var icon = document.getElementById("icon");
    icon.style.transform = "rotate(180deg)";


</script>

app/views/admins/estadisticas_en_curso.html.erb
<head>
    <link href='https://fonts.googleapis.com/css?family=Varela Round' rel='stylesheet'>
    <script src="https://kit.fontawesome.com/38e5d75ed7.js" crossorigin="anonymous"></script>
</head>

<div class="text-center">

    <h1 class="mt-4 mb-5 font">Alquileres en curso en este momento</h1>

    <% if @alquileres_en_curso.nil? %>
        <h3 class="font">No hay alquileres en curso en este momento</h3>
    <% else %>
        <div class="container d-flex">

            <% for alquiler in @alquileres_en_curso %>

                <div class="container d-flex align-items-stretch border shadow m-3"> 
                    <!--<i class="align-self-center fa-solid fa-circle-info fa-7x m-3" style="color: #f59e3e"></i>-->
                    <%if Auto.find_by(alquiler_id: alquiler.id).imagen.attached?%>
                        <%= image_tag(alquiler.auto.imagen, class:"icon_admins_list") %>
                    <%else%>
                        <i class="align-self-center fa-solid fa-car-side fa-7x m-3" style="color: #f59e3e"></i>
                    <%end%>
                    <div class="align-self-center ms-1" style="text-align: left">
                        <h5 class="font"> <i class="fa-solid fa-car me-2 fa-lg" style="color: #9B9BA0"></i> <b><%= alquiler.auto.modelo %></b> <%= alquiler.auto.patente %> </h5>
                        <h5 class="font"> <i class="fa-solid fa-user me-2 fa-lg" style="color: #9B9BA0"></i> <%= alquiler.user.first_name %> <%= alquiler.user.last_name %> </h5>
                        <h5 class="font"> <i class="fa-solid fa-calendar-alt me-2 fa-lg" style="color: #9B9BA0"></i> <%= alquiler.fecha_devolucion.strftime("%d/%m/%y") %> <%= alquiler.hora_devolucion.strftime("%H:%M:%M") %> </h5>
                    </div>
                </div>
            <% end %>
        </div>
    <%end%>
        



</div>







<style>

    .border{
        background-color: #F5F5F5;
        border: 2px solid black;
        border-radius: 15px;
    }

    .font{
        font-family: 'Varela Round';
    }

    .icon_admins_list{
        width: 120px;
        height: 120px;
        border-radius: 50%;
        margin: 10px;
    }

</style>

<script>

    var eleccion = document.getElementById("eleccion-auto");

    eleccion.addEventListener("click", function(e){
        var seleccionado = e.target.innerHTML;
        var id = e.target.id;
        var patente = id.split("_")[0];
        console.log(patente);

        modelo = seleccionado.split("-")[0];
        boldModelo = "<b>" + modelo + "</b>";

        var dropdownButton = document.getElementById("dropdown-button");
        dropdownButton.innerHTML = boldModelo + " - " + patente;


        var graficoPorAuto = document.getElementById("grafico-por-auto");
        var graficoPorAutoChildren = graficoPorAuto.children;
        for (var i = 0; i < graficoPorAutoChildren.length; i++) {
            graficoPorAutoChildren[i].hidden = true;
        }

        var conteiner = document.getElementById(patente + "-container");
        conteiner.hidden = false;

    });


</script>

app/views/admins/historial_de_uso.html.erb
<h1 class="h1 text-center">Historial del <%=@auto.modelo%> <%=@auto.anio%> </h1>
<div class="m-5">
  <hr>
  <div class="table-responsive">
    <table class="table shadow rounded" style="background-color:white;">
      <tr>
        <th class="fs-5">Auto</th>
        <th class="fs-5">Usuario</th>
        <th class="fs-5">Fecha del alquiler</th>
        <th class="fs-5">Hora del alquiler</th>
        <th class="fs-5"></th>
        <%# <th class="fs-5">eMail</th> %>
      </tr>
      <%-@alquileres.each do |alquiler|-%>
          <tr>
            <td style="font-size: 1rem"><%= @auto.modelo %> <%= @auto.anio %> </td>

            <% user = User.find(alquiler.user_id) %>
            <td style="font-size:1rem;"><%= user.first_name  %> <%= user.last_name%></td>

            <td class="" style="font-size: 1rem"><%= alquiler.fecha_alquiler %></td>

            <td style="font-size: 1rem"><%= "#{alquiler.hora_alquiler.hour}:#{alquiler.hora_alquiler.min}:#{alquiler.hora_alquiler.sec} Hs" %></td>


            <td>
                <%= link_to "Ver", "/alquiler/show/#{alquiler.id}", class: "btn btn-primary p-2" %>
            </td>

          </tr>

        <%end%>
    </table>
  </div>
</div>

app/views/admins/index.html.erb
<div>
    <% if current_admin.is_admin? %>
        <% name = "Administrador" %>
    <% else %>
        <% name = "Supervisor" %>
    <% end %>
    <h1>Main <%= name %></h1>
    <h5>Bienvenido, <%= current_admin.first_name %>!</h5>
    <p>Mi mail es <%= current_admin.email %></p>
    <br>
    <div class="container d-flex justify-content-start">
        <%= button_to "Logout", destroy_admin_session_path, method: :delete, class:"btn btn-info p-1 m-2"  %>
    </div>
</div>