config/routes.rb
Rails.application.routes.draw do

  devise_scope :admin do
    get 'admins/editSupervisor/:id', to: 'admins/registrations#editSupervisor', as: 'editSupervisor'
  end

  devise_scope :admin do
    put 'admins/updateSupervisor/:id', to: 'admins/registrations#updateSupervisor', as: 'updateSupervisor'
  end

  devise_scope :admin do
    delete 'admins/deleteSupervisor/:id', to: 'admins/registrations#deleteSupervisor', as: 'deleteSupervisor'
  end

  devise_scope :user do
    put 'users/edit', to: 'users/registrations#updateUser', as: 'updateUser'
  end

  put "/autos/cambiarEstado/:auto_id", to: "autos#cambiarEstado", as: "cambiarEstado"


  resources :autos, only: [:new, :create, :edit, :update]
  resources :precios
  resources :reportes, only: [:show]
	resources :locations, only: :create
  # devise_for :supervisors, controllers: {
  #   sessions: 'supervisors/sessions'
  # }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:index]
  resources :admins, only: [:index]

  # as :admin do
  #   get '/admins', :to => 'admins#estadisticas', :as => :admins_root # Rails 3
  # end

  as :user do
    # generate route that recives the id of a auto
    get 'users', :to => 'users#index', :as => :users_root # Rails 3
  end

  # get "admins/edit/:id", to: "admins/registrations#edit"
  # put "admins/edit/:id", to: "admins/registrations#update"

  get '/users/vehiculo/:id', :to => 'users#vehiculo', :as => :vehiculo
  get '/admins/listar_usuarios', :to => 'admins#listar_usuarios'
  get '/admins/listar_no_validados', :to => 'admins#listar_no_validados'
  get '/admins/listar_supervisores', :to => 'admins#listar_supervisores'
  get '/autos', :to => 'autos#listadoDeAutos'

  get '/admins/showUser/:id', :to => 'admins#showUser', as: 'showUser'

  root "main#home"

  get '/wallets/:user_id', :to => 'wallets#mostrar_wallet'
  put '/wallets/cargar_saldo/:user_id', :to => 'wallets#cargar_saldo'

  get '/precios', :to => 'precios#index'
  post '/precios/editarPrecio', :to => 'precios#editarPrecio'

  put '/cards/create/', :to => 'cards#create'
  get '/users/vista_mapa', :to => 'users#vista_mapa'
  get '/cards/create', :to => 'cards#new', :as => 'new_card'

  put '/admins/updateUserStatus/:user_id', :to => 'admins#updateUserStatus'

  get '/users/vista_alquiler', :to => 'users#vista_alquiler'

  put '/users/finalizar_alquiler', :to => 'users#finalizar_alquiler'

  post '/users/alquilar/:auto_id', :to => 'users#alquilar'

  get '/users/certificado', :to => 'users#certificado'

  get '/abrir_cerrar/:id', :to => 'users#abrir_cerrar'

  get 'alquiler/resumen', :to => 'users#resumen', :as => 'resumen'

  get '/admins/listado_reportes/pendientes', :to => 'reportes#index_pendientes'

  get '/admins/listado_reportes/atendidos', :to => 'reportes#index_atendidos'

  get '/admins/listado_reportes/finalizados', :to => 'reportes#index_finalizados'

  get '/admins/estadisticas', :to => 'admins#estadisticas'

  get '/admins/estadisticas/alquileres', :to => 'admins#estadisticas_alquileres'

  get '/admins/estadisticas/ganancias', :to => 'admins#estadisticas_ganancias'

  get '/admins/estadisticas/reportes', :to => 'admins#estadisticas_reportes'

  get '/admins/estadisticas/en_curso', :to => 'admins#estadisticas_en_curso'

  get '/users/reportes/new', :to => 'reportes#new', :as => 'new_reporte'

  post '/users/reportes/create', :to => 'reportes#create', :as => 'create_reporte'

  put '/users/prolongar_alquiler', :to => 'users#prolongar_alquiler'

  put '/atender_reporte/:id', :to => 'reportes#atender_reporte'

  put '/finalizar_reporte/:id', :to => 'reportes#finalizar_reporte'

  get '/admins/historial_de_uso/:id', :to => 'admins#historial_de_uso'

  get '/alquiler/show/:id', :to => 'admins#show_alquiler'

  get '/', :to => 'main#home'

  #match "*path" => redirect("/"), via: [:get, :post]   #DEJAR SIEMPRE AL FINAL

end

app/models/auto.rb
class Auto < ApplicationRecord
    validates :patente, presence: true, uniqueness: true
    validates :modelo, presence: true
    validates :porcentaje_combustible, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
    validates :estado, presence: true
    validates :anio, presence: true, numericality: { greater_than_or_equal_to: 1900, less_than_or_equal_to: 2022 }
    validates :tipo_de_caja, presence: true
    validates :tipo_de_combustible, presence: true
    validates :color, presence: true
    validate :patente_format
    has_one_attached :imagen
    has_many :alquilers, dependent: :destroy

    # make patente validates with a regex
    def patente_format
        if patente.present? && !patente.match?(/\A^[a-zA-Z]{3}-[0-9]{3}$\z/) && !patente.match?(/\A^[a-zA-Z]{2}-[0-9]{3}-[a-zA-Z]{2}$\z/)
            errors.add(:patente, "formato inválido, debe ser AAA-000 o AA-000-AA")
        end
    end
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController

  layout "for_admins"
  before_action :authenticate_admin!
  # before_action :set_search

  def set_search
    @q = Auto.ransack(params[:q])
  end

  def cambiarEstado
    @auto = Auto.find(params[:auto_id])
    @auto.estado = estado_params[:estado]
    @auto.save
    redirect_to autos_path
  end

  def listadoDeAutos
    # @q = Auto.ransack(params[:q])
    # @autos = @q.result(distinct: true)
    @autos = Auto.all.order(anio: :desc)
  end

  def new
    @auto = Auto.new
  end

  def create
    @auto = Auto.new(auto_params)
    @auto.location_point = "-34.905085, -57.939161"
    @auto.is_open = false
    if @auto.save
      redirect_to autos_path
    else
      render :new
    end
  end

  def edit
    @auto = Auto.find(params[:id])
  end

  def update
    @auto = Auto.find(params[:id])
    if @auto.update(auto_params)
      redirect_to autos_path
    else
      render :edit
    end
  end

  def destroy
    @auto = Auto.find(params[:id])
    @auto.destroy
    redirect_to autos_path
  end

  def abrir_cerrar
    @auto = Auto.find(params[:id])
    if @auto.is_open?
      @auto.is_open = false
    else
      @auto.is_open = true
    end
    @auto.save
    redirect_to users_path
  end

  def auto_params
    params.require(:auto).permit(:imagen, :patente, :modelo, :porcentaje_combustible, :estado, :anio, :tipo_de_caja, :tipo_de_combustible, :color)
  end

  def estado_params
    params.require(:auto).permit(:estado)
  end

end

app/helpers/autos_helper.rb
module AutosHelper
end

app/views/autos/edit.html.erb
<h1>Editar Vehículo</h1>

<%= render "error_messages", resource: @auto %>

<% if @auto.estado != "Ocupado"%>

  <% if @auto.imagen.attached?%>
    <% if @auto.imagen.representable?%>
      <%= image_tag(@auto.imagen, width: 400)%> <br>
      <%= link_to "Descargar Imágen", rails_blob_path(@auto.imagen, disposition: "attachment") %>
    <%end%>
  <%else%>
    <label>No hay imagen Disponible</label>
  <%end%>


<%# button to view history of car %>
<%= link_to "Historial de uso", "/admins/historial_de_uso/#{@auto.id}", class:"btn btn-info"%>
<div style="padding-left: 20px">
  <%= form_for (@auto) do |f| %>
    <br>
    <div>
      <%= f.label :imagen %><br>
      <div class="col-md-2">
        <%= f.file_field :imagen%>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :patente %><br>
        <div class="col-md-2">
          <%= f.text_field :patente , class:"form-control", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :anio, "Año" %><br>
        <div class="col-md-2">
          <%= f.number_field :anio, class:"form-control", required: true, min:1950, max:2022%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :modelo %><br>
        <div class="col-md-2">
          <%= f.text_field :modelo, class:"form-control", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :tipo_de_caja %><br>
        <div class="col-md-2">
          <%= f.select :tipo_de_caja, ["Automatico", "Manual"],  class:"form-select", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :tipo_de_combustible %><br>
        <div class="col-md-2" >
          <%= f.select :tipo_de_combustible, ["Diesel", "Nafta", "Electrico"], class:"form-control", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :porcentaje_combustible %><br>
        <div class="col-md-2">
          <%= f.number_field :porcentaje_combustible, in:0.0..100.0, step: 0.1, class:"form-control", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :estado %><br>
        <div class="col-md-2">
          <%= f.select :estado, ["Disponible", "En mantenimiento", "Necesita Atencion", "Inhabilitado"], class:"form-select", required: true%>
        </div>
      </div>

      <div class="form-group" style="margin-bottom: 5px">
        <%= f.label :color %><br>
        <div class="col-md-2">
          <%= f.color_field :color, class:"form-control", required: true%>
        </div>
      </div>

      <div style="margin-top: 10px">
        <%= f.submit class:"btn btn-info" %>
      </div>

  <%end%>
</div>
<%else%>
  <div class="alert alert-warning alert-dismissible fade show p-2 m-4" role="alert" style="margin-bottom:1px; font-size:22px;">
          <strong>¡Atención!</strong> El auto de patente <%= @auto.patente %> no se puede editar porque se encuentra ocupado.
        </div>
<%end%>

app/views/autos/listadoDeAutos.html.erb
<h1 class="h1 text-center">Vehículos</h1>
<% if current_admin.is_admin? %>
<br>
<div class="text-center">
  <%= link_to "Crear nuevo Vehiculo", new_auto_path, :class => "btn btn-primary " %>
</div>
<br>
<% end %>

<div class="container-sm">
 <hr>
  <div class="table-responsive" >
    <table class="table shadow rounded" style="background-color:white;">
      <tr>
        <th class="fs-5 text-center">FOTO</th>
        <%# <th class="fs-5 text-center">FOTO</th> %>
        <th class="fs-5 text-center">PATENTE</th>
        <th class="fs-5 text-center">MODELO</th>
        <th class="fs-5 text-center">AÑO</th>
        <th class="fs-5 text-center">TIPO DE COMBUSTIBLE</th>
        <th class="fs-5 text-center">TIPO DE CAJA</th>
        <th class="fs-5 text-center">COMBUSTIBLE</th>
        <th class="fs-5 text-center">COLOR</th>
        <th class="fs-5 text-center">ESTADO</th>
        <th class="fs-5 text-center">MODIFICAR</th>
      </tr>
      <%-@autos.each do |auto|-%>
        <tr>
        <!--<td class="font-size: 1rem text-center"><%= auto.id %></td>-->
        <td class="font-size: 1rem text-center">
        <%if auto.imagen.attached?%>
          <%= image_tag(auto.imagen, class:"icon_admins_list") %></td>
        <%else%>
          <label>Sin Foto</label>
        <%end%>
        </td>
        <td class="font-size: 1rem text-center"><%= auto.patente %></td>
        <td class="font-size: 1rem text-center"><%= auto.modelo %></td>
        <td class="font-size: 1rem text-center"><%= auto.anio %></td>
        <td class="font-size: 1rem text-center"><%= auto.tipo_de_combustible %></td>
        <td class="font-size: 1rem text-center"><%= auto.tipo_de_caja %></td>
        <td class="font-size: 1rem text-center"><%= auto.porcentaje_combustible %></td>
        <td class="font-size: 1rem text-center" style="background-color: <%= auto.color %>; border-width: thin;"></td>
        <td class="font-size: 1rem text-center"><%= auto.estado %></td>
        <% if current_admin.is_admin? %>
        <td class="font-size: 1rem text-center"><%= link_to "Editar", edit_auto_path(auto.id), :class => "btn btn-primary" %></td>
        <% else %>
        <td class="text-center">
          <%= form_for(auto, as: auto, url: "/autos/cambiarEstado/#{auto.id}" , html: { method: :put }) do |f| %>
          <%= f.select :estado, ["Disponible", "Ocupado", "En mantenimiento", "Necesita Atencion", "Inhabilitado"], class:"form-select", required: true%>
          <%= f.submit "Actualizar Estado", class:"btn btn-info p-1 mt-1" %>
          <% end %>
        <% end %>
        </td>
        </tr>
      <%end%>
    </table>
  </div>
</div>

<%# <style>
 #myInput {
  background-image: url('/css/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}

#myTable {
  border-collapse: collapse; /* Collapse borders */
  width: 100%; /* Full-width */
  border: 1px solid #ddd; /* Add a grey border */
  font-size: 18px; /* Increase font-size */
}

#myTable th, #myTable td {
  text-align: left; /* Left-align text */
  padding: 12px; /* Add padding */
}

#myTable tr {
  /* Add a bottom border to all table rows */
  border-bottom: 1px solid #ddd;
}

#myTable tr.header, #myTable tr:hover {
  /* Add a grey background color to the table header and on hover */
  background-color: #f1f1f1;
}
</style> %>

app/views/autos/new.html.erb
<h1>Ingrese los datos del Nuevo Vehiculo</h1>

<%= render "error_messages", resource: @auto %>

<% auto = Auto.new %>
<div style="padding-left: 20px" class="mb-2">
  <%= form_for (@auto) do |f| %>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :imagen %><br>
      <div class="col-md-2">
        <%= f.file_field :imagen %>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :patente %><br>
      <div class="col-md-2">
        <%= f.text_field :patente , class:"form-control", required: true %>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :anio, "Año" %><br>
      <div class="col-md-2">
        <%= f.number_field :anio, class:"form-control", required: true, min:1900, max:2022 %>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :modelo %><br>
      <div class="col-md-2">
        <%= f.text_field :modelo, class:"form-control", required: true%>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :tipo_de_caja %><br>
      <div class="col-md-2">
        <%= f.select :tipo_de_caja, ["Automatico", "Manual"],  class:"form-select", required: true%>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :tipo_de_combustible %><br>
      <div class="col-md-2" >
        <%= f.select :tipo_de_combustible, ["Diesel", "Nafta", "Electrico"], class:"form-control", required: true%>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :porcentaje_combustible %><br>
      <div class="col-md-2">
        <%= f.number_field :porcentaje_combustible, in:0.0..100.0, step: 0.1, class:"form-control", required: true%>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :estado %><br>
      <div class="col-md-2">
        <%= f.select :estado, ["Disponible", "Ocupado", "En mantenimiento", "Necesita Atencion", "Inhabilitado"], class:"form-select", required: true%>
      </div>
    </div>

    <div class="form-group" style="margin-bottom: 5px">
      <%= f.label :color %><br>
      <div class="col-md-2">
        <%= f.color_field :color, class:"form-control", required: true%>
      </div>
    </div>

    <div style="margin-top: 10px">
      <%= f.submit class:"btn btn-info" %>
    </div>

  <%end%>
</div>