config/routes.rb
Rails.application.routes.draw do

  devise_scope :admin do
    get 'admins/editSupervisor/:id', to: 'admins/registrations#editSupervisor', as: 'editSupervisor'
  end

  devise_scope :admin do
    put 'admins/updateSupervisor/:id', to: 'admins/registrations#updateSupervisor', as: 'updateSupervisor'
  end

  devise_scope :admin do
    delete 'admins/deleteSupervisor/:id', to: 'admins/registrations#deleteSupervisor', as: 'deleteSupervisor'
  end

  devise_scope :user do
    put 'users/edit', to: 'users/registrations#updateUser', as: 'updateUser'
  end

  put "/autos/cambiarEstado/:auto_id", to: "autos#cambiarEstado", as: "cambiarEstado"


  resources :autos, only: [:new, :create, :edit, :update]
  resources :precios
  resources :reportes, only: [:show]
	resources :locations, only: :create
  # devise_for :supervisors, controllers: {
  #   sessions: 'supervisors/sessions'
  # }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  resources :users, only: [:index]
  resources :admins, only: [:index]

  # as :admin do
  #   get '/admins', :to => 'admins#estadisticas', :as => :admins_root # Rails 3
  # end

  as :user do
    # generate route that recives the id of a auto
    get 'users', :to => 'users#index', :as => :users_root # Rails 3
  end

  # get "admins/edit/:id", to: "admins/registrations#edit"
  # put "admins/edit/:id", to: "admins/registrations#update"

  get '/users/vehiculo/:id', :to => 'users#vehiculo', :as => :vehiculo
  get '/admins/listar_usuarios', :to => 'admins#listar_usuarios'
  get '/admins/listar_no_validados', :to => 'admins#listar_no_validados'
  get '/admins/listar_supervisores', :to => 'admins#listar_supervisores'
  get '/autos', :to => 'autos#listadoDeAutos'

  get '/admins/showUser/:id', :to => 'admins#showUser', as: 'showUser'

  root "main#home"

  get '/wallets/:user_id', :to => 'wallets#mostrar_wallet'
  put '/wallets/cargar_saldo/:user_id', :to => 'wallets#cargar_saldo'

  get '/precios', :to => 'precios#index'
  post '/precios/editarPrecio', :to => 'precios#editarPrecio'

  put '/cards/create/', :to => 'cards#create'
  get '/users/vista_mapa', :to => 'users#vista_mapa'
  get '/cards/create', :to => 'cards#new', :as => 'new_card'

  put '/admins/updateUserStatus/:user_id', :to => 'admins#updateUserStatus'

  get '/users/vista_alquiler', :to => 'users#vista_alquiler'

  put '/users/finalizar_alquiler', :to => 'users#finalizar_alquiler'

  post '/users/alquilar/:auto_id', :to => 'users#alquilar'

  get '/users/certificado', :to => 'users#certificado'

  get '/abrir_cerrar/:id', :to => 'users#abrir_cerrar'

  get 'alquiler/resumen', :to => 'users#resumen', :as => 'resumen'

  get '/admins/listado_reportes/pendientes', :to => 'reportes#index_pendientes'

  get '/admins/listado_reportes/atendidos', :to => 'reportes#index_atendidos'

  get '/admins/listado_reportes/finalizados', :to => 'reportes#index_finalizados'

  get '/admins/estadisticas', :to => 'admins#estadisticas'

  get '/admins/estadisticas/alquileres', :to => 'admins#estadisticas_alquileres'

  get '/admins/estadisticas/ganancias', :to => 'admins#estadisticas_ganancias'

  get '/admins/estadisticas/reportes', :to => 'admins#estadisticas_reportes'

  get '/admins/estadisticas/en_curso', :to => 'admins#estadisticas_en_curso'

  get '/users/reportes/new', :to => 'reportes#new', :as => 'new_reporte'

  post '/users/reportes/create', :to => 'reportes#create', :as => 'create_reporte'

  put '/users/prolongar_alquiler', :to => 'users#prolongar_alquiler'

  put '/atender_reporte/:id', :to => 'reportes#atender_reporte'

  put '/finalizar_reporte/:id', :to => 'reportes#finalizar_reporte'

  get '/admins/historial_de_uso/:id', :to => 'admins#historial_de_uso'

  get '/alquiler/show/:id', :to => 'admins#show_alquiler'

  get '/', :to => 'main#home'

  #match "*path" => redirect("/"), via: [:get, :post]   #DEJAR SIEMPRE AL FINAL

end

app/views/admins/partials/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    
    <!-- Section: Social media -->

    <!-- Section: Form -->
    <%
=begin%>
 <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example21" class="form-control" />
              <label class="form-label" for="form5Example21">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section> 
<%
=end%>
    <!-- Section: Form -->

    <!-- Section: Text -->
    <%
=begin%>
 <section class="mb-4">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum
        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam
        eum harum corrupti dicta, aliquam sequi voluptate quas.
      </p>
    </section>
  </div> 
<%
=end%>

  <!-- Copyright -->
  <div class="text-center p-3 row" style="background-color: rgba(0, 0, 0, 0.2); height: 80px;">
    <div class="col vetical" style="color:red; height: 20px; margin:0; padding:0;">
      © 2020 Copyright:
      <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <div class="col vetical" style="margin-bottom: 0px; height: 20;">
      <section class="mb-4" style="margin:0; padding:0;">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>

        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>

        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>

        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
    </div>
  </div>
  <!-- Copyright -->
</footer>

<style>
  .footer {
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: red;
    color: white;
    text-align: center;
  }
  
  .vetical{
    display: flex;
    align-items: center;
    justify-content: center;
  }

</style>

app/views/admins/partials/_menu.html.erb
<nav class="navbar navbar-expand-lg bg-warning">
  <div class="container container-fluid">
    <%= link_to "Alquilapp", root_path, class:"navbar-brand" %>
    <%# <a class="navbar-brand" href="#">Alquilapp</a> %>
    <%# <%= button_to "Listar autos", autos_path,  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <div class="btn-group nav-item">
          <%= link_to "Estadisticas", '/admins/estadisticas/', class:"nav-link" %>
          <button type="button" class="btn nav-link dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Reservas", '/admins/estadisticas/alquileres', class:"dropdown-item" %></li>
            <% if current_admin.is_admin %>
            <li><%= link_to "Ganancias", '/admins/estadisticas/ganancias', class:"dropdown-item" %></li>
            <% end %>
            <li><%= link_to "En curso", '/admins/estadisticas/en_curso', class:"dropdown-item" %></li>
            <li><%= link_to "Reportes", '/admins/estadisticas/reportes', class:"dropdown-item" %></li>
          </ul>
        </div>
        <%# <li class="nav-item"> %>
          <%# <%= link_to "Listar autos", "/autos", class:"nav-link" %>
        <%# </li> %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Reportes
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Pendientes", '/admins/listado_reportes/pendientes', class:"dropdown-item" %> </li>
            <!-- no lo descomenten, es al pedo-->
            <li> <%#= link_to "Atendidos", '/admins/listado_reportes/atendidos', class:"dropdown-item" %> </li>
            <!---->
            <li> <%= link_to "Finalizados", '/admins/listado_reportes/finalizados', class:"dropdown-item" %> </li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Vehiculos
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Listar", '/autos', class:"dropdown-item" %> </li>
            <% if current_admin.is_admin %>
            <li> <%= link_to "Nuevo", '/autos/new', class:"dropdown-item" %> </li>
              <li> <%= link_to "Precio", '/precios', class:"dropdown-item" %> </li>
            <% end %>
          </ul>
        </li>
        <% if current_admin.is_admin %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Supervisores
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Listar", '/admins/listar_supervisores', class:"dropdown-item" %> </li>
            <li> <%= link_to "Nuevo", '/admins/sign_up', class:"dropdown-item" %> </li>
          </ul>
        </li>
        <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Usuarios
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to "Todos", admins_listar_usuarios_path, class:"dropdown-item" %> </li>
            <li> <%= link_to "No validados", admins_listar_no_validados_path, class:"dropdown-item" %> </li>
          </ul>
        </li>

        <!--<li class="nav-item">
          <%= link_to "Listar usuarios", admins_listar_usuarios_path, class:"nav-link" %>
        </li>-->
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>

      <%= image_tag "logo.png", width: 20, class:"p-1 icon_img_admins d-flex" %>
      <%= button_to "Logout", destroy_admin_session_path, method: :delete, class:"btn btn-info", style:"background-color:white; border-color:white"  %>
    </div>
  </div>
</nav>